### PR TITLE
[SQL-Playground] Improve Input

### LINKED ISSUE #1004: [SQL-Playground] Improve Input
Currently we do not support systax highlighting
For better feedback the written SQL text should be highlighted.
here it should be checked if the input heading "Abgabe Text:" can simply be changed to "SQL-Query"

**Technologies must be approved by team leaders bevore implementation.**

**current:**
image

**better:**
image

### PR DESCRIPTION
**Pull request by SiarNoozai**
resolves #1004 
improves user input with highlighted syntax (sql)

### CODE REVIEW

**Review by pdrtzk — CHANGES_REQUESTED** [review]
Please remove the `package.json` and `package-lock.json` files from the `modules/` and `modules/fbs-core/` directionaries. 

These are not neccessary there and already exist inside `modules/fbs-core/web/`.

**Review by pdrtzk — DISMISSED** [review]

**Review by TimonPllkrn — CHANGES_REQUESTED** [review]
On Firefox:
- [ ] With multiline input the cursor remains in the first line and only moves further backwards

- [ ] You cannot click with the mouse in the lines below the first one

**Review by Medienkunzt — APPROVED** [review]
Now it works fine for me in firefox, edge, opera, chrome.

**Review by pdrtzk — DISMISSED** [review]

**Review by TimonPllkrn — CHANGES_REQUESTED** [review]
filter `new lines` and `tabs` from sql string

**Review by Medienkunzt — APPROVED** [review]
Works great, I am very satisfied!

**Review by TimonPllkrn — APPROVED** [review]

**Pull request merged**
