### PR TITLE
Add coverage

### PR DESCRIPTION
**Pull request by Zitrone44**
This add coverage reporting.

### CODE REVIEW

**Review by mxsph — COMMENTED** [review]
The coverage is currently only for the ws, wouldn't it make sense to add them for the master-runer as well?

**Comment by Zitrone44** [comment]
> The coverage is currently only for the ws, wouldn't it make sense to add them for the master-runer as well?

Yes that would be a good idea

**Comment by andrej-sajenko** [comment]
> > The coverage is currently only for the ws, wouldn't it make sense to add them for the master-runer as well?
> 
> Yes that would be a good idea.

Can you add it : )

**Comment by Zitrone44** [comment]
> > > The coverage is currently only for the ws, wouldn't it make sense to add them for the master-runer as well?
> > 
> > 
> > Yes that would be a good idea.
> 
> Can you add it : )

Yes currently working on it.

**Comment by Zitrone44** [comment]
Now reports coverage for ws and master-runner.

**Review by mxsph — APPROVED** [review]
:+1:

**Comment by andrej-sajenko** [comment]
Looks fine to me, the only change I want to suggest is to adjust the threshold for failure. Our current code coverage is 13%, which is below the standard used by coverage. I do not recall how, but I know that you can adjust the default coverage threshold. Please set it to 13% (and max. decrease to 5%) at the start so that our pull request that include fixes, etc. are checked successfully. For further features and big changes we will need to create tests to pass the test.

**Comment by Zitrone44** [comment]
> it to 13% (and max. decrease to 5%) at the start so that our pull request that include fixes, etc. are checked successfully. For further features and big changes we will need to create tests to pass the test.

Ok :+1:

**Pull request merged**
