### PR TITLE
Update goto links

### PR DESCRIPTION
**Pull request by Zitrone44**
This PR adds automatic course join to goto links and adds copy buttons to the goto link dialog.

### CODE REVIEW

**Review by mxsph — CHANGES_REQUESTED** [review]
Looks good so far :+1:

I only have a few comments:

- I would  give a visual feedback after clicking the copy button that the link has been copied.
- The copy button should have a tooltip.
- Maybe an explanation of what the links are good for would be useful, but I'm not quite sure how exactly they should be displayed. @kimiannalena  any ideas?

**Comment by kimiannalena** [comment]
Agreeing with @mxsph.
Since the explanations of the links is rather long and similar, I would not put them in a tooltip, but show them as text above the input fields. I suggest changing the content to `Kopiere den Link, um ihn in Moodle oder anderen externen Seiten einzubinden. Er leitet Studierende zu der Kursseite bzw. der Feedback_App weiter.`

**Review by mxsph — APPROVED** [review]
👍

**Review by kimiannalena — APPROVED** [review]
Looks good

**Pull request merged**
