### PR TITLE
Refactoring of the sql checker

### LINKED ISSUE #728: Refactoring of SQL-Checker
In the SQL Checker, many methods are called multiple times. This affects performance. This issue aims to revise the code to minimize method calls. In general, the code should be analyzed and, where possible, designed better.

### PR DESCRIPTION
**Pull request by Jonas960**
Closes #728

### CODE REVIEW

**Comment by Jonas960** [comment]
During testing, an error was discovered that occurs with queries that cannot be parsed. It will be fixed soon and tested again.

**Review by VladikB — DISMISSED** [review]
Seems to work now

**Comment by Jonas960** [comment]
@VladikB 

- [ ] Unparsable queries works but they doesn't get saved in the mongodb collection "NotParsable"
- [ ] Tablechecker doesn't work anymore. Detection of tables works but if you give a right solution it still says "wrong". This error happens with and without "union".

**Review by JaWiss — APPROVED** [review]
Tested it with multiple datasets ,worked well and handled all data correctly

**Comment by Jonas960** [comment]
Has been tested and works.

**Review by Medienkunzt — APPROVED** [review]

**Pull request merged**
