### PR TITLE
[sql-checker] Remove hardcoded mongodb database name

### LINKED ISSUE #943: [SQL-Checker] remove hard coded `sql-checker` Database-Name
**Is your feature request related to a problem? Please describe.**
Currently the `sql-checker` Databasename is hard coded.

**Describe the solution you'd like**
The Databasename should be read from the mongodb string.

**Additional context**
* https://docs.python.org/3/library/urllib.parse.html

### LINKED ISSUE #1002: Add sql-checker to docker-compose
**Is your feature request related to a problem? Please describe.**
Currently the container for the sql-checker must be build manually.

**Describe the solution you'd like**
The sql-checker should be build with docker-compose like the bash checker.

### PR DESCRIPTION
**Pull request by Zitrone44**
closes #943 
closes #1002

### CODE REVIEW

**Review by Jonas960 — CHANGES_REQUESTED** [review]
@Zitrone44 

image

It does not work properly. I get the message that there is no default database defined for the MongoDB.

**Review by mxsph — APPROVED** [review]

**Review by Jonas960 — CHANGES_REQUESTED** [review]
@Zitrone44 Sample solutions are still missing the cid. These must be added.

**Comment by Jonas960** [comment]
@Zitrone44 The code works very well but I found one more problem. The new keywords are not displayed in the frontend when errors occur. 
image

**Comment by Jonas960** [comment]
@Zitrone44 unfortunately, there is now another problem. After a submission, it is processed correctly by the sql-checker. However, when reading the mongodb, an error occurs. Here is an export from the logfile of the core.

```
org.mongodb.driver.connection            : Opened connection [connectionId{localValue:3, serverValue:53}] to mongodb:27017

Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [java.lang.Boolean] to type [scala.Option<?>]] with root cause
```

**Review by Jonas960 — DISMISSED** [review]
@Zitrone44 there was a little problem with the error messages of select and where attributes. I exchanged this messages and now it works fine for me.

**Comment by Zitrone44** [comment]
@Jonas960 your [Merge Commit](https://github.com/thm-mni-ii/feedbacksystem/pull/976/commits/668ef41fb18c57c9f4d64ecd55c232f2c4d7a08e) seems to have introduced unrelated commits into this branch, which cause merge conflicts could you remove them so that this can be merged?

**Review by Jonas960 — APPROVED** [review]

**Review by mxsph — APPROVED** [review]

**Pull request merged**
