### PR TITLE
Add subtask system

### PR DESCRIPTION
**Pull request by Zitrone44**

### CODE REVIEW

**Review by mxsph — CHANGES_REQUESTED** [review]
During testing I noticed a couple of errors:

- [x] `fbs.sql` & `init.sql` are no longer needed and can be deleted.
- [x] The migration of the database has deleted my whole database, because the `number` in the database mirgration table was not present all steps were executed which removed all data. Should we possibly remove the drop table statements in the file `01_init.sql` as these are the problem?
- [x] I would set the `cursor` in the clickable parts of the input fields to pointer (so it is more obvious that you can click on them).
  
   
  Frame 1

- [ ] When editing a `calculation task` all fields are empty which is why you always have to fill them in again.
- [x] Typo: `Einhabeparameter` (when creating a task)
- [ ] This text does not adapt if you change the setting for it
   
  Frame 2

- [x] Tasks of type `text/zip-file` cannot be created anymore
- [ ] Change task: Change from calculation to `text` (etc.) not possible (maybe deactivate?)
- [x] comma instead of dot as separator (may be adjustable)
- [x] Multiple checkers do not work? (at least with the type `calculation`)
- [x] console.logs + error messages in the browser console
- [ ] Why exactly do subtasks have points again and are not only passed or not passed? Because if you want to have more points it is easy to add more subtasks. So isn't this more complicated and doesn't bring much?

**Comment by Zitrone44** [comment]
> Why exactly do subtasks have points again and are not only passed or not passed? Because if you want to have more points it is easy to add more subtasks. So isn't this more complicated and doesn't bring much?

The reason why subtasks have points is that this way teachers can weight subtasks in relation to each other. For example, in a curve dissection task it is possible to give more points for the analysis of the asymptotic behavior than for finding the null points. Without having to divide the task.

**Review by mxsph — CHANGES_REQUESTED** [review]
- [x] I would make the points optional in the calculation and set them to 1 by default.
- [x] The editing still does not work properly because the Excel file is no longer available.
- [x] There are still points in the input parameters
  
  grafik

- [x] I would only show the subtasks table if there are any.
- [x] In the overview (in the course and at the task in the upper right corner) there is always a `-` displayed for tasks without subtasks (maybe we should restore the allte display for these tasks).

- [ ] ~After migration of an old system, it is no longer possible to display or create tasks.~ 
- [x] There was also a bug in the `master-runner` which caused that no more checks were executed. The passing of the additional parameter `subTaskFileLocation` has led to an error (I have already fixed this error :smile:)

**Comment by Zitrone44** [comment]
>     * [ ]  After migration of an old system, it is no longer possible to display or create tasks.
>       E.g. you get this error:

`media_information` was added before the migration system and is therefor in `01_init.sql`, because `01_init.sql` is no longer executed because of the changes in 3ff28f32309d2701208d2b8cc7f51a6d9d46c8b0 `media_information` has to be added manually.

```SQL
alter table task
	add media_information json null;
```

**Review by mxsph — CHANGES_REQUESTED** [review]
It looks like everything is working now :tada: 

I have only two suggestions for improvement:

- [x] Since the table for the subtask shows which subtasks were passed anyway, could it only be displayed here whether the task was passed or not? (Maybe you could add icons next to the points in the sub-task list to show if passed/not passed)

  grafik

- [ ] We could use the opportunity to pack the results of the tasks without subtasks into the route `/courses/:id/tasks/results`. This way, when a course is called, only this one route would be called and not all sub-tasks would be queried (if this is more complicated, you can also create an issue for this and we will adjust it later, I just thought that this fix would make sense in this PR :smile:).

**Review by mxsph — CHANGES_REQUESTED** [review]
There is unfortunately still an error in the calculation whether a task (without subtasks) was passed or not:

- (Task with one checker) Submission 1. :heavy_check_mark:, Submission 2. :heavy_multiplication_x: ->:heavy_multiplication_x: (But should be :heavy_check_mark:, because the task was passed with one submission).
- (Task with two checkers) Submission (C1) :heavy_check_mark: (C2) :heavy_multiplication_x: -> :heavy_check_mark: (But should be :heavy_multiplication_x:, since one check was not passed)

**Review by mxsph — APPROVED** [review]
:tada:

**Pull request merged**
